// ============================================================
// DHANDHA — Central Game Configuration
// 40-Tile Board — Indian States, Cities & Monuments
// ============================================================

import type {
  BoardTileConfig,
  CharacterConfig,
  PropertyGroupConfig,
} from '../types/game';

export const GAME_CONFIG = {
  BOARD_SIZE: 40,
  MAX_PLAYERS: 4,
  MIN_PLAYERS: 2,
  STARTING_MONEY: 15000,
  PASS_GO_AMOUNT: 5000,
  GAME_DURATION_MINUTES: 25,
  LEGAL_TROUBLE_TURNS: 3,
  LEGAL_TROUBLE_BAIL: 1500,
  LEGAL_TROUBLE_POSITION: 30,
  BANKRUPTCY_THRESHOLD: 0,
  MAX_EVENTS_LOG: 50,
  MAX_CHAT_MESSAGES: 100,
  CONSECUTIVE_DOUBLES_LIMIT: 3,
  TAUNT_RATE_LIMIT_MS: 5000,
  CHAT_RATE_LIMIT_MS: 1000,
  ROOM_TTL_SECONDS: 7200,
  GAME_TTL_SECONDS: 10800,

  LEVEL_LABELS: ['🏚️ Land', '🏪 Shop', '🏬 Store', '🏢 Complex', '🏨 Mega Business'],

  PLAYER_COLORS: ['#f59e0b', '#3b82f6', '#10b981', '#f43f5e'],
  PLAYER_AVATARS: ['🔴', '🔵', '🟢', '🟡'],

  // ─── Characters ─────────────────────────────────────────────
  CHARACTERS: [
    {
      id: 'trader',
      name: 'The Trader',
      hindiName: 'Vyapari',
      emoji: '🧑‍💼',
      description: 'Master negotiator. Born to wheel and deal.',
      abilityName: 'Sharp Deal',
      abilityDescription: 'Trade offers stay open 30s longer. Can counter-offer once per turn.',
      color: '#f59e0b',
    },
    {
      id: 'food-king',
      name: 'The Food King',
      hindiName: 'Bhojan Samrat',
      emoji: '🍛',
      description: 'Khana business mein sabse zyaada paisa hai.',
      abilityName: 'Taste of Success',
      abilityDescription: 'Market & food businesses generate +20% revenue.',
      color: '#ef4444',
    },
    {
      id: 'tech-founder',
      name: 'The Tech Founder',
      hindiName: 'Startup Guru',
      emoji: '💻',
      description: 'Bengaluru aur Hyderabad mein taqat hai.',
      abilityName: 'Agile Growth',
      abilityDescription: 'Bengaluru & Hyderabad upgrade costs -20%.',
      color: '#3b82f6',
    },
    {
      id: 'builder',
      name: 'The Builder',
      hindiName: 'Nirmata',
      emoji: '🏗️',
      description: 'Ek ek inth se mahal banao.',
      abilityName: 'Master Builder',
      abilityDescription: 'All business upgrade costs 15% cheaper.',
      color: '#8b5cf6',
    },
    {
      id: 'influencer',
      name: 'The Influencer',
      hindiName: 'Content Creator',
      emoji: '🎬',
      description: 'Viral ho jaana hi business hai.',
      abilityName: 'Viral Boost',
      abilityDescription: 'Once per game, boost one business revenue by 50% for 2 turns.',
      color: '#ec4899',
    },
    {
      id: 'sports-star',
      name: 'The Sports Star',
      hindiName: 'Cricket Hero',
      emoji: '🏏',
      description: 'Cricket mein hi nahi, business mein bhi champion.',
      abilityName: 'Champion Momentum',
      abilityDescription: 'During Cricket Fever events, collect double pass-GO bonus.',
      color: '#10b981',
    },
  ] as CharacterConfig[],

  // ─── 10 State-Coded Property Groups + Hawai Adda ───────────
  PROPERTY_GROUPS: [
    { group: 'red',      name: 'Maharashtra (MH)',     color: '#dc2626', textColor: '#fff', bonusPercent: 25, tileIds: [1, 2, 3] },
    { group: 'orange',   name: 'Gujarat (GJ)',         color: '#ea580c', textColor: '#fff', bonusPercent: 25, tileIds: [5, 6, 7] },
    { group: 'cyan',     name: 'Rajasthan (RJ)',       color: '#0891b2', textColor: '#fff', bonusPercent: 20, tileIds: [10, 11] },
    { group: 'pink',     name: 'Tamil Nadu (TN)',      color: '#db2777', textColor: '#fff', bonusPercent: 20, tileIds: [14, 15] },
    { group: 'green',    name: 'Kerala (KL)',          color: '#16a34a', textColor: '#fff', bonusPercent: 20, tileIds: [17, 18] },
    { group: 'purple',   name: 'Uttar Pradesh (UP)',   color: '#9333ea', textColor: '#fff', bonusPercent: 25, tileIds: [21, 22, 23] },
    { group: 'blue',     name: 'West Bengal (WB)',     color: '#2563eb', textColor: '#fff', bonusPercent: 25, tileIds: [25, 26, 27] },
    { group: 'gold',     name: 'Punjab (PB)',          color: '#ca8a04', textColor: '#fff', bonusPercent: 20, tileIds: [30, 31] },
    { group: 'indigo',   name: 'Karnataka (KA)',       color: '#6366f1', textColor: '#fff', bonusPercent: 20, tileIds: [34, 35] },
    { group: 'teal',     name: 'Telangana (TG)',       color: '#0d9488', textColor: '#fff', bonusPercent: 20, tileIds: [37, 38] },
    { group: 'railway',  name: 'Hawai Adda (Airports)', color: '#475569', textColor: '#fff', bonusPercent: 0,  tileIds: [4, 16, 24, 36] },
  ] as PropertyGroupConfig[],

  // ─── Market Events ────────────────────────────────────────────
  MARKET_EVENTS: [
    {
      id: 'cricket-fever',
      name: 'Cricket Fever! 🏏',
      icon: '🏏',
      description: 'IPL Season hai! Sports & entertainment businesses mein 50% boom!',
      groupMultipliers: {},
      flatBonus: 1000,
      turns: 2,
    },
    {
      id: 'diwali-boom',
      name: 'Diwali Boom! 🪔',
      icon: '🪔',
      description: 'Diwali sale shuru! Retail mein 2× revenue!',
      groupMultipliers: { red: 2, orange: 2 },
      flatBonus: 0,
      turns: 1,
    },
    {
      id: 'it-boom',
      name: 'IT Hiring Boom! 💻',
      icon: '💻',
      description: 'Tech companies bhaar rahi hain! Blue & Gold group 40% boost!',
      groupMultipliers: { blue: 1.4, gold: 1.4 },
      flatBonus: 0,
      turns: 2,
    },
    {
      id: 'market-crash',
      name: 'Market Crash! 📉',
      icon: '📉',
      description: 'Sensex girta ja raha hai! Sab businesses temporarily weak.',
      groupMultipliers: {},
      flatBonus: -500,
      turns: 1,
    },
    {
      id: 'monsoon',
      name: 'Monsoon Season! 🌧️',
      icon: '🌧️',
      description: 'Baarish mein business slow. Railways halted. -20% revenue everywhere.',
      groupMultipliers: { railway: 0 },
      flatBonus: -300,
      turns: 2,
    },
  ],

  // ─── Desi Events ─────────────────────────────────────────────
  DESI_EVENTS: [
    { id: 'chai-break',   icon: '🍵', name: 'Chai Break!',          description: 'Chai pi lo yaar! Recover karo.',                           amount: 300,   type: 'gain' as const },
    { id: 'wedding-tax',  icon: '💒', name: 'Wedding Season!',       description: 'Bhai ki shaadi ka gift toh dena padega.',                  amount: -500,  type: 'lose' as const },
    { id: 'jugaad',       icon: '🔧', name: 'Jugaad Kiya!',          description: 'Desi jugaad se problem solve! Aage badho 3 kadam.',        amount: 3,     type: 'move' as const },
    { id: 'viral-post',   icon: '📱', name: 'Viral Ho Gaya!',        description: 'Social media pe viral post! Business boom.',               amount: 800,   type: 'gain' as const },
    { id: 'traffic-jam',  icon: '🚗', name: 'Traffic Jam!',          description: 'Delhi mein traffic jam! Ek turn chhodna padega.',          amount: 0,     type: 'skip' as const },
    { id: 'govt-scheme',  icon: '🏛️', name: 'Sarkari Yojana!',       description: 'Government ka naya business scheme! Subsidy mili.',        amount: 500,   type: 'gain' as const },
    { id: 'power-cut',    icon: '💡', name: 'Power Cut!',            description: 'Bijli chali gayi! Kaam ruk gaya. Lose ek turn.',           amount: 0,     type: 'skip' as const },
    { id: 'biryani-deal', icon: '🍖', name: 'Biryani Wala Deal!',    description: 'Sab ko biryani khilani padegi. Paisa de do.',             amount: -400,  type: 'lose' as const },
    { id: 'ipl-bet',      icon: '🏆', name: 'IPL Betting Jeet!',     description: 'Sahi team lagi! Bada profit.',                             amount: 1200,  type: 'gain' as const },
    { id: 'auto-overcharge', icon: '🛺', name: 'Auto Overcharge!',   description: 'Auto bhaiya ne zyaada le liya.',                          amount: -200,  type: 'lose' as const },
  ],

  // ─── Luck Events ─────────────────────────────────────────────
  LUCK_EVENTS: [
    { id: 'tax-refund',    icon: '💰', name: 'Tax Refund!',       description: 'Income tax refund aa gaya! Sarkar ne paisa wapas kiya.',  amount: 1000,  type: 'gain' as const },
    { id: 'lucky-bet',     icon: '🎰', name: 'Lucky Bet!',        description: 'Horse race mein laga daanv jeet gaya!',                   amount: 1500,  type: 'gain' as const },
    { id: 'bad-investment',icon: '📉', name: 'Bad Investment!',   description: 'IPO mein paisa duba. Bhai, research karo pehle.',         amount: -800,  type: 'lose' as const },
    { id: 'found-money',   icon: '💵', name: 'Found Money!',      description: 'Purani jacket mein paise mile!',                          amount: 500,   type: 'gain' as const },
    { id: 'hospital-bill', icon: '🏥', name: 'Hospital Bill!',    description: 'Dawai ka bill aa gaya. Health is wealth bhai.',           amount: -1000, type: 'lose' as const },
    { id: 'bank-bonus',    icon: '🏦', name: 'Bank FD Matured!',  description: 'FD mature hui! Fixed deposit ka fayda.',                  amount: 600,   type: 'gain' as const },
  ],

  // ─── The 40-Tile Board (Positions 0–39 on a 14×8 Perimeter Grid) ─────
  BOARD: [
    // ══════════════════════════════════════════════════════════════
    // BOTTOM ROW (positions 0–13, left → right)
    // ══════════════════════════════════════════════════════════════
    {
      id: 0,
      type: 'start',
      name: 'DHANDHA START',
      icon: '⭐',
      description: 'All players start here! Collect ₹5,000 every time you pass START.',
    },
    // State 1: MAHARASHTRA (3 cities)
    {
      id: 1,
      type: 'property',
      name: 'Mumbai Marine Drive',
      state: 'MAHARASHTRA',
      city: 'Mumbai',
      monument: 'Marine Drive',
      icon: '🏛️',
      description: 'Iconic Queen\'s Necklace waterfront. Premium commercial hub.',
      group: 'red',
      color: '#dc2626',
      price: 3500,
      revenue: [350, 1750, 4400, 8800],
      upgradeCosts: [1750, 2800, 4200],
    },
    {
      id: 2,
      type: 'property',
      name: 'Pune IT Park',
      state: 'MAHARASHTRA',
      city: 'Pune',
      monument: 'Hinjawadi IT Park',
      icon: '💼',
      description: 'Booming software & automobile corridor in Maharashtra.',
      group: 'red',
      color: '#dc2626',
      price: 3000,
      revenue: [300, 1500, 3800, 7600],
      upgradeCosts: [1500, 2400, 3600],
    },
    {
      id: 3,
      type: 'property',
      name: 'Nagpur Orange Hub',
      state: 'MAHARASHTRA',
      city: 'Nagpur',
      monument: 'Zero Mile Stone',
      icon: '🍊',
      description: 'Geographical center of India and logistics superpower.',
      group: 'red',
      color: '#dc2626',
      price: 2800,
      revenue: [280, 1400, 3500, 7000],
      upgradeCosts: [1400, 2240, 3360],
    },
    // Airport 1
    {
      id: 4,
      type: 'railway',
      name: 'Mumbai Hawai Adda',
      state: 'MAHARASHTRA',
      city: 'Mumbai',
      monument: 'CSM International Airport',
      icon: '✈️',
      description: 'Chhatrapati Shivaji Maharaj Airport. High passenger air traffic.',
      group: 'railway',
      color: '#475569',
      price: 4000,
      railwayRevenue: [500, 1000, 2000, 4000],
    },
    // State 2: GUJARAT (3 cities)
    {
      id: 5,
      type: 'property',
      name: 'Ahmedabad Textile Hub',
      state: 'GUJARAT',
      city: 'Ahmedabad',
      monument: 'Sabarmati Riverfront',
      icon: '🧵',
      description: 'Manchester of the East. Heritage and thriving business center.',
      group: 'orange',
      color: '#ea580c',
      price: 2600,
      revenue: [260, 1300, 3300, 6600],
      upgradeCosts: [1300, 2080, 3120],
    },
    {
      id: 6,
      type: 'property',
      name: 'Surat Diamond Bourse',
      state: 'GUJARAT',
      city: 'Surat',
      monument: 'Diamond Bourse',
      icon: '💎',
      description: 'World\'s diamond cutting capital and silk textile market.',
      group: 'orange',
      color: '#ea580c',
      price: 2400,
      revenue: [240, 1200, 3000, 6000],
      upgradeCosts: [1200, 1920, 2880],
    },
    {
      id: 7,
      type: 'property',
      name: 'Vadodara Palace',
      state: 'GUJARAT',
      city: 'Vadodara',
      monument: 'Laxmi Vilas Palace',
      icon: '🏰',
      description: 'Grand royal heritage and flourishing chemical industry.',
      group: 'orange',
      color: '#ea580c',
      price: 2200,
      revenue: [220, 1100, 2800, 5600],
      upgradeCosts: [1100, 1760, 2640],
    },
    // Petrol Pump 1 (Utility)
    {
      id: 8,
      type: 'property',
      name: 'Bharat Petrol Pump',
      icon: '⛽',
      description: 'Busy national highway fuel & EV charging utility station.',
      group: 'orange',
      color: '#ea580c',
      price: 2500,
      revenue: [250, 1250, 3100, 6200],
      upgradeCosts: [1250, 2000, 3000],
    },
    // Tax 1 (Fine)
    {
      id: 9,
      type: 'tax',
      name: 'INCOME TAX',
      icon: '💸',
      description: 'Income Tax Assessment notice! Pay ₹1,500 to the central treasury.',
      taxAmount: 1500,
    },
    // State 3: RAJASTHAN (2 cities)
    {
      id: 10,
      type: 'property',
      name: 'Jaipur Hawa Mahal',
      state: 'RAJASTHAN',
      city: 'Jaipur',
      monument: 'Hawa Mahal',
      icon: '🏰',
      description: 'Palace of Winds. World-famous Pink City jewel.',
      group: 'cyan',
      color: '#0891b2',
      price: 2000,
      revenue: [200, 1000, 2500, 5000],
      upgradeCosts: [1000, 1600, 2400],
    },
    {
      id: 11,
      type: 'property',
      name: 'Udaipur Lake Palace',
      state: 'RAJASTHAN',
      city: 'Udaipur',
      monument: 'Lake Pichola',
      icon: '⛵',
      description: 'City of Lakes. Luxury heritage tourism destination.',
      group: 'cyan',
      color: '#0891b2',
      price: 1800,
      revenue: [180, 900, 2300, 4600],
      upgradeCosts: [900, 1440, 2160],
    },
    // Luck / Reward
    {
      id: 12,
      type: 'luck',
      name: 'KISMET DRAW',
      icon: '🎰',
      description: 'Kismet card! Draw from the deck for cash prizes or wild surprises.',
    },
    // Corner: Chai Break
    {
      id: 13,
      type: 'desi-event',
      name: 'CHAI BREAK',
      icon: '☕',
      description: 'Tapri time! Settle down and have hot cutting chai & samosas.',
    },

    // ══════════════════════════════════════════════════════════════
    // RIGHT COLUMN (positions 14–19, bottom → top)
    // ══════════════════════════════════════════════════════════════
    // State 4: TAMIL NADU (2 cities)
    {
      id: 14,
      type: 'property',
      name: 'Chennai Marina Beach',
      state: 'TAMIL NADU',
      city: 'Chennai',
      monument: 'Marina Beach',
      icon: '🏖️',
      description: 'Automobile capital and scenic coastal trade hub.',
      group: 'pink',
      color: '#db2777',
      price: 2200,
      revenue: [220, 1100, 2800, 5600],
      upgradeCosts: [1100, 1760, 2640],
    },
    {
      id: 15,
      type: 'property',
      name: 'Madurai Meenakshi',
      state: 'TAMIL NADU',
      city: 'Madurai',
      monument: 'Meenakshi Amman Temple',
      icon: '🛕',
      description: 'Ancient temple city and South Indian cultural epicenter.',
      group: 'pink',
      color: '#db2777',
      price: 2000,
      revenue: [200, 1000, 2500, 5000],
      upgradeCosts: [1000, 1600, 2400],
    },
    // Airport 2
    {
      id: 16,
      type: 'railway',
      name: 'Chennai Hawai Adda',
      state: 'TAMIL NADU',
      city: 'Chennai',
      monument: 'Chennai International Airport',
      icon: '✈️',
      description: 'Major South Indian international gateway airport.',
      group: 'railway',
      color: '#475569',
      price: 4000,
      railwayRevenue: [500, 1000, 2000, 4000],
    },
    // State 5: KERALA (2 cities)
    {
      id: 17,
      type: 'property',
      name: 'Kochi Spice Port',
      state: 'KERALA',
      city: 'Kochi',
      monument: 'Chinese Fishing Nets',
      icon: '🚢',
      description: 'Queen of the Arabian Sea. International spice trade port.',
      group: 'green',
      color: '#16a34a',
      price: 2400,
      revenue: [240, 1200, 3000, 6000],
      upgradeCosts: [1200, 1920, 2880],
    },
    {
      id: 18,
      type: 'property',
      name: 'Munnar Tea Hills',
      state: 'KERALA',
      city: 'Munnar',
      monument: 'Anamudi Peak',
      icon: '🍃',
      description: 'God\'s Own Country lush tea plantations and hill retreat.',
      group: 'green',
      color: '#16a34a',
      price: 2200,
      revenue: [220, 1100, 2800, 5600],
      upgradeCosts: [1100, 1760, 2640],
    },
    // Fine / Event
    {
      id: 19,
      type: 'tax',
      name: 'TRAFFIC CHALLAN',
      icon: '🚨',
      description: 'Over-speeding traffic challan! Pay ₹1,000 fine to the city police.',
      taxAmount: 1000,
    },

    // ══════════════════════════════════════════════════════════════
    // TOP ROW (positions 20–33, right → left)
    // ══════════════════════════════════════════════════════════════
    // Corner: Free Parking / Rest
    {
      id: 20,
      type: 'free-rest',
      name: 'FREE PARKING',
      icon: '🚗',
      description: 'Rest area! No taxes, no rents. Enjoy a peaceful pit-stop.',
    },
    // State 6: UTTAR PRADESH (3 cities)
    {
      id: 21,
      type: 'property',
      name: 'Varanasi Ghats',
      state: 'UTTAR PRADESH',
      city: 'Varanasi',
      monument: 'Dashashwamedh Ghat',
      icon: '🪔',
      description: 'Spiritual capital of India. Massive devotee and tourist footfall.',
      group: 'purple',
      color: '#9333ea',
      price: 2800,
      revenue: [280, 1400, 3500, 7000],
      upgradeCosts: [1400, 2240, 3360],
    },
    {
      id: 22,
      type: 'property',
      name: 'Lucknow Hazratganj',
      state: 'UTTAR PRADESH',
      city: 'Lucknow',
      monument: 'Bara Imambara',
      icon: '👑',
      description: 'City of Nawabs. Iconic shopping street and royal cuisine.',
      group: 'purple',
      color: '#9333ea',
      price: 3000,
      revenue: [300, 1500, 3800, 7600],
      upgradeCosts: [1500, 2400, 3600],
    },
    {
      id: 23,
      type: 'property',
      name: 'Agra Taj View',
      state: 'UTTAR PRADESH',
      city: 'Agra',
      monument: 'Taj Mahal',
      icon: '🏛️',
      description: 'Wonder of the World! Global tourist magnet and luxury hospitality.',
      group: 'purple',
      color: '#9333ea',
      price: 3200,
      revenue: [320, 1600, 4000, 8000],
      upgradeCosts: [1600, 2560, 3840],
    },
    // Airport 3
    {
      id: 24,
      type: 'railway',
      name: 'Delhi IGI Hawai Adda',
      state: 'DELHI',
      city: 'New Delhi',
      monument: 'Indira Gandhi International',
      icon: '✈️',
      description: 'Busiest aviation hub in South Asia with world-class terminals.',
      group: 'railway',
      color: '#475569',
      price: 4000,
      railwayRevenue: [500, 1000, 2000, 4000],
    },
    // State 7: WEST BENGAL (3 cities)
    {
      id: 25,
      type: 'property',
      name: 'Kolkata Howrah Bridge',
      state: 'WEST BENGAL',
      city: 'Kolkata',
      monument: 'Howrah Bridge',
      icon: '🌉',
      description: 'City of Joy. Heritage trade, sweets, and booming commerce.',
      group: 'blue',
      color: '#2563eb',
      price: 3200,
      revenue: [320, 1600, 4000, 8000],
      upgradeCosts: [1600, 2560, 3840],
    },
    {
      id: 26,
      type: 'property',
      name: 'Darjeeling Tea Hills',
      state: 'WEST BENGAL',
      city: 'Darjeeling',
      monument: 'Tiger Hill',
      icon: '☕',
      description: 'Champagne of Teas. World-renowned hill station retreat.',
      group: 'blue',
      color: '#2563eb',
      price: 2800,
      revenue: [280, 1400, 3500, 7000],
      upgradeCosts: [1400, 2240, 3360],
    },
    {
      id: 27,
      type: 'property',
      name: 'Siliguri Corridor',
      state: 'WEST BENGAL',
      city: 'Siliguri',
      monument: 'Corridor Gateway',
      icon: '🌲',
      description: 'Gateway to the North East. Major trade and transport junction.',
      group: 'blue',
      color: '#2563eb',
      price: 2600,
      revenue: [260, 1300, 3300, 6600],
      upgradeCosts: [1300, 2080, 3120],
    },
    // Petrol Pump 2 (Utility)
    {
      id: 28,
      type: 'property',
      name: 'Indian Oil Petrol Pump',
      icon: '⛽',
      description: 'Major state highway fuel station and logistics service center.',
      group: 'blue',
      color: '#2563eb',
      price: 2500,
      revenue: [250, 1250, 3100, 6200],
      upgradeCosts: [1250, 2000, 3000],
    },
    // Tax 2 (Fine)
    {
      id: 29,
      type: 'tax',
      name: 'GST & WEALTH TAX',
      icon: '📑',
      description: 'Annual corporate GST and wealth levy! Pay ₹2,000 to the treasury.',
      taxAmount: 2000,
    },
    // State 8: PUNJAB (2 cities)
    {
      id: 30,
      type: 'property',
      name: 'Amritsar Golden Temple',
      state: 'PUNJAB',
      city: 'Amritsar',
      monument: 'Harmandir Sahib',
      icon: '🛕',
      description: 'The Golden Temple. Divine spiritual center and massive hospitality hub.',
      group: 'gold',
      color: '#ca8a04',
      price: 3400,
      revenue: [340, 1700, 4200, 8400],
      upgradeCosts: [1700, 2720, 4080],
    },
    {
      id: 31,
      type: 'property',
      name: 'Ludhiana Industrial Hub',
      state: 'PUNJAB',
      city: 'Ludhiana',
      monument: 'Clock Tower',
      icon: '🏭',
      description: 'Manchester of India. Powerhouse of garments and bicycle manufacturing.',
      group: 'gold',
      color: '#ca8a04',
      price: 3200,
      revenue: [320, 1600, 4000, 8000],
      upgradeCosts: [1600, 2560, 3840],
    },
    // Reward / Festival
    {
      id: 32,
      type: 'treasure',
      name: 'DIWALI KHAZANA',
      icon: '🪔',
      description: 'Diwali festive jackpot! Collect ₹1,500 celebratory bonus.',
      festivalBonus: 1500,
    },
    // Corner: Jail
    {
      id: 33,
      type: 'legal-trouble',
      name: 'POLICE THANA',
      icon: '⚖️',
      description: 'Police Thana! Pay ₹1,500 bail or roll doubles to get out.',
    },

    // ══════════════════════════════════════════════════════════════
    // LEFT COLUMN (positions 34–39, top → bottom)
    // ══════════════════════════════════════════════════════════════
    // State 9: KARNATAKA (2 cities)
    {
      id: 34,
      type: 'property',
      name: 'Bengaluru Silicon Valley',
      state: 'KARNATAKA',
      city: 'Bengaluru',
      monument: 'Vidhana Soudha',
      icon: '💻',
      description: 'India\'s Tech Capital. Startups, venture capital, and IT unicorns.',
      group: 'indigo',
      color: '#6366f1',
      price: 3800,
      revenue: [380, 1900, 4800, 9600],
      upgradeCosts: [1900, 3040, 4560],
    },
    {
      id: 35,
      type: 'property',
      name: 'Mysuru Royal Palace',
      state: 'KARNATAKA',
      city: 'Mysuru',
      monument: 'Mysore Palace',
      icon: '👑',
      description: 'City of Palaces. Renowned for silk, sandalwood, and royal heritage.',
      group: 'indigo',
      color: '#6366f1',
      price: 3200,
      revenue: [320, 1600, 4000, 8000],
      upgradeCosts: [1600, 2560, 3840],
    },
    // Airport 4
    {
      id: 36,
      type: 'railway',
      name: 'Bengaluru Hawai Adda',
      state: 'KARNATAKA',
      city: 'Bengaluru',
      monument: 'Kempegowda International Airport',
      icon: '✈️',
      description: 'Kempegowda Airport. Rapidly expanding garden terminal.',
      group: 'railway',
      color: '#475569',
      price: 4000,
      railwayRevenue: [500, 1000, 2000, 4000],
    },
    // State 10: TELANGANA (2 cities)
    {
      id: 37,
      type: 'property',
      name: 'Hyderabad Cyber Towers',
      state: 'TELANGANA',
      city: 'Hyderabad',
      monument: 'HITEC City',
      icon: '🏢',
      description: 'Cyberabad tech epicenter and global pharma giant hub.',
      group: 'teal',
      color: '#0d9488',
      price: 3600,
      revenue: [360, 1800, 4500, 9000],
      upgradeCosts: [1800, 2880, 4320],
    },
    {
      id: 38,
      type: 'property',
      name: 'Hyderabad Charminar',
      state: 'TELANGANA',
      city: 'Hyderabad',
      monument: 'Charminar',
      icon: '🕌',
      description: 'Historical masterpiece, pearl markets, and world-famous Biryani.',
      group: 'teal',
      color: '#0d9488',
      price: 3400,
      revenue: [340, 1700, 4200, 8400],
      upgradeCosts: [1700, 2720, 4080],
    },
    // Desi Jugaad Event
    {
      id: 39,
      type: 'desi-event',
      name: 'DESI JUGAAD',
      icon: '🔧',
      description: 'Indian smart jugaad! Gain ₹800 bonus or move ahead 3 steps.',
    },
  ] as BoardTileConfig[],
} as const;

export function getTileById(id: number): BoardTileConfig {
  const tile = GAME_CONFIG.BOARD[id];
  if (!tile) throw new Error(`Invalid tile ID: ${id}`);
  return tile;
}

export function getGroupConfig(group: string): PropertyGroupConfig | undefined {
  return GAME_CONFIG.PROPERTY_GROUPS.find(g => g.group === group);
}

export function getPurchasableTileIds(): number[] {
  return GAME_CONFIG.BOARD
    .filter(t => t.type === 'property' || t.type === 'railway')
    .map(t => t.id);
}

export type GameConfig = typeof GAME_CONFIG;
